services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: space_weather_station
    environment:
      - MSSQL_SA_PASSWORD=p@ssWord1234
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: